name: lint

on:
  push:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Ruff
        run: pip install ruff

      - name: Ruff check
        run: ruff check .


  test:
    runs-on: ubuntu-latest
    needs: lint

    env:
      POSTGRES_USER: ${{secrets.POSTGRES_USER}}
      POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD}}
      POSTGRES_DB_AUTH: auth
      POSTGRES_DB_UNIVERSITY: university

      AUTH_SERVICE_INTERNAL_URL: http://auth:8000
      AUTH_SERVICE_API_URL: http://localhost:8000

      UNIVERSITY_SERVICE_INTERNAL_URL: http://university:8000
      UNIVERSITY_SERVICE_API_URL: http://localhost:8001

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Start services
        run: docker compose up -d

      - name: Debug env
        run: env | grep POSTGRES

      - name: Docker ps
        run: docker ps -a

      - name: Show docker logs
        if: failure()
        run: docker compose logs

      - name: Run tests with Allure
        run: pytest --alluredir=allure-results
        continue-on-error: true

      - name: Upload Allure results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-results
          path: allure-results


  report:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Download Allure results
        uses: actions/download-artifact@v4
        with:
          name: allure-results

      - name: Install Allure
        run: |
          sudo apt-get update
          sudo apt-get install -y default-jre
          wget https://github.com/allure-framework/allure2/releases/download/2.27.0/allure-2.27.0.tgz
          tar -xzf allure-2.27.0.tgz
          sudo mv allure-2.27.0 /opt/allure
          sudo ln -s /opt/allure/bin/allure /usr/bin/allure

      - name: Generate Allure report
        run: allure generate allure-results -o allure-report --clean

      - name: Deploy report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: allure-report
          destination_dir: allure