name: API Pipeline

on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # линтер
      - name: Install Ruff
        run: pip install ruff

      - name: Run Ruff
        run: ruff check .

      # Docker
      - name: Build services
        run: docker compose build

      - name: Start services
        run: docker compose up -d

      - name: Wait for services
        run: sleep 15

      - name: Run tests
        run: docker compose run --rm auth pytest -v

      - name: Stop services
        run: docker compose down